spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-atjone-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atjone-test
#保存为UTF-8格式